# Generated by Django 5.0.6 on 2025-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
