# Generated by Django 5.0.6 on 2025-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_client', '0002_otp_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLogs',
            fields=[
                ('pk_smslogs', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
