# Generated by Django 5.0.6 on 2025-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_client', '0003_smslogs_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslogs',
            name='status',
            field=models.CharField(choices=[('0', 'FAILED'), ('1', 'SUCCESS'), ('2', 'FAILED')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
